# Object database
OBJ_AREA_RATIO_RANGE = 1
OBJ_DISTANCE_RATIO_RANGE = 1
OBJ_ANGLE_RANGE = 10

OBJ_AREA_DEVIATION = 5
OBJ_DISTANCE_DEVIATION = 5
OBJ_ANGLE_DEVIATION = 2


# Document database
DOC_AREA_RATIO_RANGE = 1
DOC_ANGLE_RANGE = 1

DOC_AREA_DEVIATION = 5
DOC_ANGLE_DEVIATION = 2
DOC_BOUNDING_BOXES_DEVIATION = 20
