# Object database
OPEN_CV_MIN_THRESHOLD = 0.5


OBJ_AREA_RATIO_RANGE = 0.1
OBJ_DISTANCE_RATIO_RANGE = 0.999
OBJ_ANGLE_RANGE = 10

OBJ_AREA_DEVIATION = 5
OBJ_DISTANCE_DEVIATION = 5
OBJ_ANGLE_DEVIATION = 2


# Document database
OCR_MIN_THRESHOLD = 90

DOC_AREA_RATIO_RANGE = 0.1
DOC_ANGLE_RANGE = 1
