# Object database
OPEN_CV_MIN_THRESHOLD = 0.5
OBJ_AREA_RATIO_RANGE = 0.1
OBJ_DISTANCE_RATIO_RANGE = 0.999
OBJ_ANGLE_RANGE = 10


# Document database
OCR_MIN_THRESHOLD = 90

DOC_AREA_RATIO_RANGE = 0.1
DOC_ANGLE_RANGE = 1
